name: Maven Test Execution with Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Install dependencies
    - name: Install dependencies
      run: mvn install -DskipTests

    # Step 5: Run AllScript Tests
    - name: Run AllScript Test
      run: mvn test -Dsurefire.suiteXmlFiles=./testng.xml

    # Step 6: Generate TestNG HTML Report
    - name: Generate TestNG Report
      run: mvn surefire-report:report-only
      env:
        MAVEN_OPTS: "-Djava.awt.headless=true"

    # Step 7: Archive TestNG Results
    - name: Archive Surefire Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/surefire-reports/

    # Step 8: Archive TestNG HTML Report
    - name: Archive TestNG HTML Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: testng-html-report
        path: target/site/surefire-report.html
