name: Selenium Test Execution with Extent Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Install dependencies
    - name: Install dependencies
      run: mvn install -DskipTests

    # Step 5: Run Tests
    - name: Run Tests
      env:
        BASE_URL: "http://34.28.190.18/" # Provide the application URL as an environment variable
      run: mvn test -Dsurefire.suiteXmlFiles=./testng.xml

    # Step 6: Debug Directory Structure (Verify Reports and Screenshots)
    - name: Debug Directory Structure
      if: always()
      run: ls -R

    # Step 7: Archive Extent Reports and Screenshots
    - name: Archive Extent Reports and Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          **/report.html
          **/screenshots/* # Include all screenshots captured during the tests

    # Step 8: Add Report Link to Summary
    - name: Add Summary for Report
      if: always()
      run: |
        echo "### Test Report Generated" >> $GITHUB_STEP_SUMMARY
        echo "Download the report and screenshots from the 'Artifacts' section above." >> $GITHUB_STEP_SUMMARY
