name: Maven Test Execution with Extent Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Install dependencies
    - name: Install dependencies
      run: mvn install -DskipTests

    # Step 5: Run AllScript Tests
    - name: Run AllScript Test
      run: mvn test -Dsurefire.suiteXmlFiles=./testng.xml

    # Step 6: Archive Extent Reports
    - name: Archive Extent Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: extent-reports
        path: test-output/ExtentReports/* # Adjust if reports are in a different location

    # Step 7: Display Report Link in Summary
    - name: Add Extent Report Link to Summary
      if: always()
      run: |
        echo "### Extent Report :link:" >> $GITHUB_STEP_SUMMARY
        echo "[View Extent Report](./artifacts/extent-reports/index.html)" >> $GITHUB_STEP_SUMMARY

    # Step 8: Debug Report Path (Optional)
    - name: Debug Report Path
      if: always()
      run: ls -R test-output/ExtentReports/
