name: Maven Test Execution with Extent Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Install dependencies
    - name: Install dependencies
      run: mvn install -DskipTests

    # Step 5: Run Tests
    - name: Run AllScript Test
      run: mvn test -Dsurefire.suiteXmlFiles=./testng.xml

    # Step 6: Debug Directory Structure
    - name: Debug Directory Structure
      if: always()
      run: ls -R

    # Step 7: Archive Extent Report
    - name: Archive Extent Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: extent-reports
        path: src/main/java/report.html # Update to the actual path

    # Step 8: Add Summary Message
    - name: Add Summary for Report
      if: always()
      run: |
        echo "### Extent Report Generated" >> $GITHUB_STEP_SUMMARY
        echo "Download the report from the 'Artifacts' section on this page." >> $GITHUB_STEP_SUMMARY
