name: Selenium Test Execution with Extent Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clean Workspace
    - name: Clean Workspace
      run: rm -rf * || true

    # Step 2: Checkout the Repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 3: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 4: Cache Maven Dependencies
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 5: Install Dependencies
    - name: Install Dependencies
      run: mvn install -DskipTests

    # Step 6: Run Tests
    - name: Run Tests
      env:
        BASE_URL: "http://34.28.190.18/" # Provide the application URL as an environment variable
      run: |
        # Remove previous reports if they exist
        if [ -f "./extent-reports/report.html" ]; then
          rm -f ./extent-reports/report.html
        fi
        mvn test -Dsurefire.suiteXmlFiles=./testng.xml

    # Step 7: Debug Directory Structure
    - name: Debug Directory Structure
      if: always()
      run: find . -name 'report.html'

    # Step 8: Archive Extent Reports and Screenshots
    - name: Archive Extent Reports and Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          extent-reports/report.html
          extent-reports/screenshots/* # Update paths to match your report and screenshot directory

    # Step 9: Add Report Link to Summary
    - name: Add Summary for Report
      if: always()
      run: |
        echo "### Test Report Generated" >> $GITHUB_STEP_SUMMARY
        echo "Download the report and screenshots from the 'Artifacts' section above." >> $GITHUB_STEP_SUMMARY
