name: Selenium Test Execution with Extent Reports

on:
  schedule:
    - cron: '30 1 * * *' # Runs daily at 7:00 AM IST (1:30 AM UTC)
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clean Workspace
    - name: Clean Workspace
      run: rm -rf * || true

    # Step 2: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 3: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Step 4: Cache Maven Dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 5: Install Dependencies
    - name: Install Dependencies
      run: mvn install -DskipTests

    # Step 6: Run Tests
    - name: Run Tests
      env:
        BASE_URL: "http://34.28.190.18/"
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        echo "Cleaning up old reports if any..."
        rm -f ExtentReport.html
        echo "Running test suite..."
        mvn test -Dsurefire.suiteXmlFiles=./testng.xml

    # Step 7: Debug Directory Structure
    - name: Debug Directory Structure
      if: always()
      run: |
        echo "Checking directory structure for generated report..."
        find . -name 'ExtentReport.html'
        ls -R

    # Step 8: Archive Extent Reports and Screenshots
    - name: Archive Extent Reports and Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          ExtentReport.html
          screenshots/*

    # Step 9: Add Summary for Report
    - name: Add Summary for Report
      if: always()
      run: |
        if [ -f "ExtentReport.html" ]; then
          echo "### Test Report Generated" >> $GITHUB_STEP_SUMMARY
          echo "Download the report and screenshots from the 'Artifacts' section above." >> $GITHUB_STEP_SUMMARY
        else
          echo "### Test Report Missing" >> $GITHUB_STEP_SUMMARY
          echo "The test report was not generated. Check the test execution logs for details." >> $GITHUB_STEP_SUMMARY
        fi
