import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;

public class ExtentReportExample {

    public static void main(String[] args) {
        // Define the report path
        String reportPath = System.getProperty("user.dir") + "/java/reports/ExtentReport.html";

        // Initialize ExtentSparkReporter
        ExtentSparkReporter sparkReporter = new ExtentSparkReporter(reportPath);
        sparkReporter.config().setReportName("Automation Test Report");
        sparkReporter.config().setDocumentTitle("Test Execution Results");

        // Initialize ExtentReports and attach the reporter
        ExtentReports extent = new ExtentReports();
        extent.attachReporter(sparkReporter);

        // Add system info
        extent.setSystemInfo("Tester", "QA Engineer");
        extent.setSystemInfo("Environment", "Test Environment");

        // Create a test case
        ExtentTest test = extent.createTest("Verify Home Page Title");
        test.log(Status.INFO, "Launching the application");
        test.log(Status.PASS, "Home page title verified successfully");

        ExtentTest test2 = extent.createTest("Verify Login Functionality");
        test2.log(Status.INFO, "Entering login credentials");
        test2.log(Status.FAIL, "Login button is not enabled");

        // Flush report
        extent.flush();

        System.out.println("Report generated successfully at: " + reportPath);
    }
}
