name: Selenium Test Execution with Extent Reports

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clean Workspace
      run: rm -rf * || true

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Debug Maven Dependencies
      run: mvn dependency:tree

    - name: Clean Project
      run: mvn clean

    - name: Install Dependencies
      run: mvn install -DskipTests

    - name: Run Tests
      env:
        BASE_URL: "http://34.28.190.18/"
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        echo "Cleaning up old reports if any..."
        rm -f target/reports/ExtentReport.html
        echo "Running tests..."
        mvn test

    - name: Debug Directory Structure
      if: always()
      run: |
        echo "Checking directory structure for generated report..."
        find . -name 'ExtentReport.html'
        ls -R

    - name: Archive Extent Reports and Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          target/reports/ExtentReport.html
          target/screenshots/*

    - name: Add Summary for Report
      if: always()
      run: |
        if [ -f "target/reports/ExtentReport.html" ]; then
          echo "### Test Report Generated" >> $GITHUB_STEP_SUMMARY
          echo "Download the report and screenshots from the 'Artifacts' section above." >> $GITHUB_STEP_SUMMARY
        else
          echo "### Test Report Missing" >> $GITHUB_STEP_SUMMARY
          echo "The test report was not generated. Check the test execution logs for details." >> $GITHUB_STEP_SUMMARY
        fi
